#!/bin/bash

logfile="$HOME"/src/lintls/lintls.log

# For local development, assuming you've cloned this into "$HOME"/src/lintls, do something like:
# ln -s "$HOME"/src/lintls/lintls-debug-runner "$HOME"/.local/bin/lintls
echo "$0: invoked!" >>"$logfile"

export RUST_BACKTRACE=1
exec cargo run --quiet --manifest-path="$HOME"/src/lintls/Cargo.toml -- "$@" 2>>"$logfile"
